###

POST http://localhost:34702/api/v1/calc
Content-Type: application/json

{
  "operation": "add",
  "arguments": [
    2.2,
    5
  ]
}

###

POST http://localhost:34702/api/v1/calc
Content-Type: application/json

{
  "operation": "sqrt",
  "arguments": [
    25
  ]
}

###

POST http://localhost:34702/api/v1/calc
Content-Type: application/json

{
  "operation": "add",
  "arguments": [
    2.2,
    5,
    66
  ]
}

###

POST http://localhost:34702/api/v1/calc
Content-Type: application/json

{
  "arguments": [
    66
  ]
}

###
